apiVersion: v1
kind: Service

metadata:
  name: kubernetes-ci-cd-service

spec:
  type: NodePort

  selector:
    app: kubernetes-ci-cd-api

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30008